### PR TITLE
Add generic LocalizedConfiguration

### PR DESCRIPTION
**Pull request by alfogrillo**
We enjoy Swift because it is a type safe language and we can make our code more robust levereging the power of generic types.
This PR introduce the requirement both for the `Localized` and for `LocalizedConfiguration` to have an associated type `RawRepresentable` which `RawValue` type is a `String`.
Doing so we can nicely specify our keys in a single place using an enum with String rawValue and then we can pass this enum(s) around avoiding typos.

**P.S: You repo doesn't seem to have a `.xcodeproj` for the example project!**

### CODE REVIEW

**Comment by MarioIannotta** [comment]
I checked your PR and while I like the overall approach I find that forcing the developers to **always** use enums is not going to work for all of us.

My idea is to introduce one protocol that works like that:

```
public protocol LocalizedKeyProvider {
    var localizedKey: String { get }
}

public extension LocalizedKeyProvider where Self: RawRepresentable, RawValue == String {
    var localizedKey: String { rawValue }
}

extension String: LocalizedKeyProvider {
    public var localizedKey: String { self }
}
```

You'll just need to make your enums conform `LocalizedKeyProvider` like this 
```
enum ButtonKey: String, LocalizedKeyProvider {
    case normal = "Button.Title"
    case selected = "Button.Selected.Title"
    case highlighted = "Button.Highlighted.Title"
}
```

What do you think?

**Comment by alfogrillo** [comment]
You are not obligated to use `enum` to make thing working. 
You have to pass in some `RawRepresentable` with `RawValue` associated type resolved into a `String`.
I think you could do the same thing you propose above just conforming `String` to `RawRepresentable`.

For example you could do this:
```swift
extension String: RawRepresentable {
    public var rawValue: Self{
        self
    }
    
    public init(rawValue: Self) {
        self.init(stringLiteral: rawValue)
    }
}
```
You could decide to add this extension in your library or give the client apps the final decision.
What do you think?

**Comment by MarioIannotta** [comment]
I'm not a fan of that. IMO You're adding "stuff" to `String` that don't really belong there. 
I think I'll go with the additional protocol solution.

**Comment by MarioIannotta** [comment]
Implemented in https://github.com/MarioIannotta/LocalizedSwift/commit/542b4fd514076ef1567258ba8d477e7eb18f55b3. 
Thanks for the heads-up 👍

**Pull request closed without merging**
